import React, { useState } from 'react'

const BackToTop = () => {
    const [backToTop, setBackToTop] = useState(false);
    
    const scrollBack = () => {
        if(window.scrollY >= 350) {
            setBackToTop(true)
        } else {
            setBackToTop(false)
        }
    }
    window.addEventListener('scroll', scrollBack)
  return (
    <div className="back-to-top-cont">
        <a href="#first-page">
            <div className={backToTop ? "back-to-top active": "back-to-top"}>
                <div className="arrrow">⇪ </div>
            </div>
        </a>

        <p id="first-page">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.
        </p>
        
        <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore optio nulla fugiat natus. Sint in eveniet, esse quidem vero animi fugit molestias corrupti, modi commodi ducimus! Ratione blanditiis asperiores quia.
        </p>
        
    </div>
  )
}

export default BackToTop